version: '3.2'
networks:
  laravel:
    driver: bridge

services:
  app:
    build: .
    container_name: atlas-lab
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - database
  redis:
    image: redis:6.0-alpine
    networks:
      - laravel
  nginx:
    image: nginx:stable
    container_name: nginx-al
    restart: unless-stopped
    tty: true
    ports:
      - "9000:80"
      - "448:443"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database-al
    restart: always
    tty: true
    ports:
     - "3306:3306"
    environment:
     - MYSQL_DATABASE=atlas_lab
     - MYSQL_ALLOW_EMPTY_PASSWORD=true
     - MYSQL_USER=user
     - MYSQL_PASSWORD=pass
    networks:
     - laravel
    volumes:
     - ./database:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin-al
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - database
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel