version: '3.2'
networks:
  laravel:
    driver: bridge

services:
  atlas-lab-app:
    build: .
    container_name: atlas-lab-app
    restart: unless-stopped
    tty: true
    volumes:
      - ./AtlasLab:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - atlas-lab-database
  nginx:
    image: nginx:stable
    container_name: nginx-al
    restart: unless-stopped
    tty: true
    ports:
      - "9010:80"
      - "448:443"
    volumes:
      - ./AtlasLab:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  atlas-lab-database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: atlas-lab-database
    restart: always
    tty: true
    ports:
     - "3306:3306"
    environment:
     - MYSQL_DATABASE=laravel
     - MYSQL_ROOT_PASSWORD=laravel
    networks:
     - laravel
    volumes:
     - ./docker/database:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - atlas-lab-database
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel